import { Fragment } from "react";

export default function PurchasesListTab(props) {
  const {
    showNewPurchaseForm, setShowNewPurchaseForm, openNewPurchaseForm, handlePurchase,
    purchaseForm, setPurchaseForm, sessionUser, data, updatePurchaseDetail, removePurchaseDetail,
    addPurchaseDetail, purchaseTotal, money, purchasesListRows, expandedPurchaseId,
    handleTogglePurchaseDetail, purchaseDetailById, qty,
  } = props;

  return (
    <>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
        <h2>Listado de compras</h2>
        <button type="button" style={{ marginBottom: 8 }} onClick={() => (showNewPurchaseForm ? setShowNewPurchaseForm(false) : openNewPurchaseForm())}>{showNewPurchaseForm ? "Cancelar" : "Nueva compra"}</button>
      </div>
      {showNewPurchaseForm ? (
        <form className="grid" onSubmit={handlePurchase} style={{ marginBottom: 14 }}><div className="row"><select required value={purchaseForm.supplierId} onChange={(e) => setPurchaseForm((s) => ({ ...s, supplierId: e.target.value }))}><option value="">Proveedor</option>{data.suppliers.map((x) => <option key={x.id} value={x.id}>{x.businessName}</option>)}</select><input value={sessionUser.name} disabled /><select required value={purchaseForm.warehouseId} onChange={(e) => setPurchaseForm((s) => ({ ...s, warehouseId: e.target.value }))}><option value="">Deposito</option>{data.warehouses.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select required value={purchaseForm.paymentMethodId} onChange={(e) => setPurchaseForm((s) => ({ ...s, paymentMethodId: e.target.value }))}><option value="">Metodo de pago</option>{data.paymentMethods.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="date" required value={purchaseForm.purchaseDate} onChange={(e) => setPurchaseForm((s) => ({ ...s, purchaseDate: e.target.value }))} /><input placeholder="Factura" value={purchaseForm.invoiceNumber} onChange={(e) => setPurchaseForm((s) => ({ ...s, invoiceNumber: e.target.value }))} /></div><div className="tableWrap"><table style={{ minWidth: 920 }}><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio unitario</th><th>Subtotal</th><th>Accion</th></tr></thead><tbody>{purchaseForm.details.map((d, index) => <tr key={`purchase-${index}`}><td><select required value={d.productId} onChange={(e) => updatePurchaseDetail(index, "productId", e.target.value)}><option value="">Producto</option>{data.products.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></td><td><input type="number" min="0.001" step="0.001" required value={d.quantity} onChange={(e) => updatePurchaseDetail(index, "quantity", e.target.value)} /></td><td><input type="number" min="0" step="0.01" required value={d.unitPrice} onChange={(e) => updatePurchaseDetail(index, "unitPrice", e.target.value)} /></td><td>{money.format(Number(d.quantity || 0) * Number(d.unitPrice || 0))}</td><td><button type="button" className="secondary" onClick={() => removePurchaseDetail(index)}>Quitar</button></td></tr>)}</tbody></table></div><div className="row"><button type="button" className="secondary" onClick={addPurchaseDetail}>Agregar producto</button><div className="panel card"><div className="label">Total compra</div><div className="value">{money.format(purchaseTotal)}</div></div><button type="submit">Guardar compra</button><button type="button" className="secondary" onClick={() => setShowNewPurchaseForm(false)}>Cancelar</button></div></form>
      ) : null}
      <div className="tableWrap"><table><thead><tr><th>Fecha</th><th>Comprobante</th><th>Proveedor</th><th>Usuario</th><th>Deposito</th><th>Pago</th><th>Total</th><th>Detalle</th></tr></thead><tbody>{purchasesListRows.map((purchase) => <Fragment key={`purchase-list-${purchase.id}`}><tr><td>{purchase.purchaseDate}</td><td>{purchase.invoiceNumber}</td><td>{purchase.supplierName}</td><td>{purchase.userName}</td><td>{purchase.warehouseName}</td><td>{purchase.paymentMethodName}</td><td>{money.format(purchase.total)}</td><td><button type="button" className="secondary" onClick={() => handleTogglePurchaseDetail(purchase.id)}>{expandedPurchaseId === purchase.id ? "Ocultar detalle" : "Ver detalle"}</button></td></tr>{expandedPurchaseId === purchase.id ? <tr><td colSpan={8}><div className="tableWrap"><table style={{ minWidth: 500 }}><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio unitario</th><th>Subtotal</th></tr></thead><tbody>{(purchaseDetailById[purchase.id]?.PurchaseDetails || []).map((d, i) => <tr key={`purchase-list-${purchase.id}-${i}`}><td>{d.Product?.name || `Producto ${d.productId}`}</td><td>{qty.format(Number(d.quantity || 0))}</td><td>{money.format(Number(d.unitPrice || 0))}</td><td>{money.format(Number(d.quantity || 0) * Number(d.unitPrice || 0))}</td></tr>)}</tbody></table></div></td></tr> : null}</Fragment>)}</tbody></table></div>
    </>
  );
}
